// Generated by CoffeeScript 1.9.1
module.exports = {
  title: require('./title'),
  space: require('./space'),
  data: require('./data'),
  timeheadings: require('./timeheadings'),
  dayheadings: require('./dayheadings'),
  chart: require('./chart'),
  line: require('./line'),
  scatter: require('./scatter'),
  direction: require('./direction'),
  histogram: require('./histogram'),
  table: require('./table'),
  tablebytime: require('./tablebytime'),
  windrose: require('./windrose')
};
