// Generated by CoffeeScript 1.9.1
module.exports = {
  title: require('./title'),
  space: require('./space'),
  data: require('./data'),
  timeheadings: require('./time/timeheadings'),
  dayheadings: require('./time/dayheadings'),
  chart: require('./time/chart'),
  tablebytime: require('./time/tablebytime'),
  line: require('./time/line'),
  scatter: require('./time/scatter'),
  direction: require('./time/direction'),
  histogram: require('./histogram'),
  table: require('./table'),
  windrose: require('./windrose')
};
