// Generated by CoffeeScript 1.9.1
var build;

build = function(dom, items) {
  return d3.select(dom).selectAll('div.item').data(items).enter().append('div').each(function(d, i) {
    var base;
    base = d3.select(this).attr('class', "item " + d.type);
    return new window["ER" + d.type](base, d);
  });
};

d3.text('./presentation.yml', function(error, items) {
  var dom;
  items = jsyaml.load(items);
  dom = document.querySelector('body');
  return build(dom, items);
});
