// Generated by CoffeeScript 1.9.1
module.exports = {
  mount: require('./display/mount'),
  title: require('./display/title'),
  space: require('./display/space'),
  data: require('./display/data'),
  report: require('./display/report'),
  timeheadings: require('./time/timeheadings'),
  dayheadings: require('./time/dayheadings'),
  chart: require('./time/chart'),
  tablebytime: require('./time/tablebytime'),
  line: require('./time/line'),
  scatter: require('./time/scatter'),
  direction: require('./time/direction'),
  histogram: require('./xy/histogram'),
  table: require('./xy/table'),
  windrose: require('./xy/windrose')
};
