// Generated by CoffeeScript 1.9.1

/*

Represents an entire report.
Includes title, author and other metadata.
 */
var dve;

dve = require('./');

module.exports = function(dom, options) {
  var components, spec;
  components = options.components, spec = options.spec;
  return dve(dom, {
    components: components,
    spec: spec.spec
  });
};
