// Generated by CoffeeScript 1.9.1
var ERspace,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

ERspace = (function() {
  function ERspace(svg, dimensions, options) {
    this.resize = bind(this.resize, this);
    this.calculate_layout = bind(this.calculate_layout, this);
    this.svg = svg;
    this.options = options;
    this.calculate_layout(dimensions);
    this.resize(dimensions);
    hub.on('window dimensions changed', this.resize);
  }

  ERspace.prototype.calculate_layout = function(dimensions) {
    this.margin = {
      top: 0,
      right: 20,
      bottom: 0,
      left: 20
    };
    this.dimensions = {
      width: dimensions[0],
      height: this.options.height
    };
    return this.canvas = {
      top: this.margin.top,
      right: this.margin.right,
      bottom: this.margin.bottom,
      left: this.margin.left,
      width: this.dimensions.width - this.margin.left - this.margin.right,
      height: this.dimensions.height - this.margin.top - this.margin.bottom
    };
  };

  ERspace.prototype.resize = function(dimensions) {
    this.calculate_layout(dimensions);
    return this.svg.attr('width', this.dimensions.width).attr('height', this.dimensions.height);
  };

  return ERspace;

})();
