// Generated by CoffeeScript 1.9.1
var ERtitle,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

ERtitle = (function() {
  function ERtitle(svg, dimensions, options) {
    this.resize = bind(this.resize, this);
    this.calculate_layout = bind(this.calculate_layout, this);
    this.svg = svg;
    this.options = options;
    this.calculate_layout(dimensions);
    this.svg.append('g').attr('class', 'canvas').attr('transform', "translate(" + this.canvas.left + "," + this.canvas.top + ")").append('text').attr('x', 0).attr('y', 12).text(this.options.title);
    this.resize(dimensions);
    hub.on('window dimensions changed', this.resize);
  }

  ERtitle.prototype.calculate_layout = function(dimensions) {
    this.margin = {
      top: 0,
      right: 20,
      bottom: 0,
      left: 20
    };
    this.dimensions = {
      width: dimensions[0],
      height: 20
    };
    return this.canvas = {
      top: this.margin.top,
      right: this.margin.right,
      bottom: this.margin.bottom,
      left: this.margin.left,
      width: this.dimensions.width - this.margin.left - this.margin.right,
      height: this.dimensions.height - this.margin.top - this.margin.bottom
    };
  };

  ERtitle.prototype.resize = function(dimensions) {
    this.calculate_layout(dimensions);
    return this.svg.attr('width', this.dimensions.width).attr('height', this.dimensions.height);
  };

  return ERtitle;

})();
