// Generated by CoffeeScript 1.9.1
module.exports = function(delay, fn) {
  var timeout;
  timeout = null;
  return function() {
    if (timeout > -1) {
      clearTimeout(timeout);
    }
    return timeout = setTimeout(fn, delay);
  };
};
