// Generated by CoffeeScript 1.9.1
module.exports = function() {
  var body, documentElement;
  documentElement = document.documentElement;
  body = document.getElementsByTagName('body')[0];
  return [parseInt(window.innerWidth || documentElement.clientWidth || body.clientWidth), -2 + parseInt(window.innerHeight || documentElement.clientHeight || body.clientHeight)];
};
