// Generated by CoffeeScript 1.9.2
module.exports = [
  {
    time: '08/12/2014 01:00',
    location: 'Location 1',
    wd: 341,
    wsp: 4.4,
    gst: null
  }, {
    time: '08/12/2014 02:00',
    location: 'Location 1',
    wd: 314,
    wsp: 4.3,
    gst: null
  }, {
    time: '08/12/2014 03:00',
    location: 'Location 1',
    wd: 349,
    wsp: 4.2,
    gst: null
  }, {
    time: '08/12/2014 04:00',
    location: 'Location 1',
    wd: 345,
    wsp: 4.1,
    gst: 10.9
  }, {
    time: '08/12/2014 05:00',
    location: 'Location 1',
    wd: 358,
    wsp: 4.5,
    gst: null
  }, {
    time: '08/12/2014 06:00',
    location: 'Location 1',
    wd: 307,
    wsp: 4.9,
    gst: null
  }, {
    time: '08/12/2014 07:00',
    location: 'Location 1',
    wd: 338,
    wsp: 5.3,
    gst: null
  }, {
    time: '08/12/2014 08:00',
    location: 'Location 1',
    wd: 309,
    wsp: 5.5,
    gst: null
  }, {
    time: '08/12/2014 09:00',
    location: 'Location 1',
    wd: 356,
    wsp: 4.7,
    gst: null
  }, {
    time: '08/12/2014 10:00',
    location: 'Location 1',
    wd: 352,
    wsp: 4.4,
    gst: 11.5
  }, {
    time: '08/12/2014 11:00',
    location: 'Location 1',
    wd: 269,
    wsp: 4.9,
    gst: null
  }, {
    time: '08/12/2014 12:00',
    location: 'Location 1',
    wd: 96,
    wsp: 5.3,
    gst: null
  }, {
    time: '08/12/2014 13:00',
    location: 'Location 1',
    wd: 29,
    wsp: 5.8,
    gst: null
  }, {
    time: '08/12/2014 14:00',
    location: 'Location 1',
    wd: 54,
    wsp: 5.6,
    gst: null
  }, {
    time: '08/12/2014 15:00',
    location: 'Location 1',
    wd: 43,
    wsp: 5.3,
    gst: null
  }, {
    time: '08/12/2014 16:00',
    location: 'Location 1',
    wd: 21,
    wsp: 5.1,
    gst: 18.8
  }, {
    time: '08/12/2014 17:00',
    location: 'Location 1',
    wd: 33,
    wsp: 5.5,
    gst: null
  }, {
    time: '08/12/2014 18:00',
    location: 'Location 1',
    wd: 54,
    wsp: 5.9,
    gst: null
  }, {
    time: '08/12/2014 19:00',
    location: 'Location 1',
    wd: 39,
    wsp: 6.3,
    gst: null
  }, {
    time: '08/12/2014 20:00',
    location: 'Location 1',
    wd: 133,
    wsp: 6.4,
    gst: null
  }, {
    time: '08/12/2014 21:00',
    location: 'Location 1',
    wd: 175,
    wsp: 6.6,
    gst: null
  }, {
    time: '08/12/2014 22:00',
    location: 'Location 1',
    wd: 196,
    wsp: 6.8,
    gst: 16.6
  }, {
    time: '08/12/2014 23:00',
    location: 'Location 1',
    wd: 193,
    wsp: 8.5,
    gst: null
  }, {
    time: '09/12/2014 00:00',
    location: 'Location 1',
    wd: 188,
    wsp: 10.2,
    gst: null
  }, {
    time: '09/12/2014 01:00',
    location: 'Location 1',
    wd: 181,
    wsp: 12.0,
    gst: null
  }, {
    time: '09/12/2014 02:00',
    location: 'Location 1',
    wd: 182,
    wsp: 11.7,
    gst: null
  }, {
    time: '09/12/2014 03:00',
    location: 'Location 1',
    wd: 181,
    wsp: 11.4,
    gst: null
  }, {
    time: '09/12/2014 04:00',
    location: 'Location 1',
    wd: 181,
    wsp: 11.1,
    gst: 21.3
  }, {
    time: '09/12/2014 05:00',
    location: 'Location 1',
    wd: 178,
    wsp: 10.7,
    gst: null
  }, {
    time: '09/12/2014 06:00',
    location: 'Location 1',
    wd: 176,
    wsp: 10.4,
    gst: null
  }, {
    time: '09/12/2014 07:00',
    location: 'Location 1',
    wd: 174,
    wsp: 10.0,
    gst: null
  }, {
    time: '09/12/2014 08:00',
    location: 'Location 1',
    wd: 167,
    wsp: 9.6,
    gst: null
  }, {
    time: '09/12/2014 09:00',
    location: 'Location 1',
    wd: 160,
    wsp: 9.2,
    gst: null
  }, {
    time: '09/12/2014 10:00',
    location: 'Location 1',
    wd: 153,
    wsp: 8.8,
    gst: 18.8
  }, {
    time: '09/12/2014 11:00',
    location: 'Location 1',
    wd: 147,
    wsp: 9.0,
    gst: null
  }, {
    time: '09/12/2014 12:00',
    location: 'Location 1',
    wd: 142,
    wsp: 9.2,
    gst: null
  }, {
    time: '09/12/2014 13:00',
    location: 'Location 1',
    wd: 136,
    wsp: 9.4,
    gst: null
  }, {
    time: '09/12/2014 14:00',
    location: 'Location 1',
    wd: 132,
    wsp: 9.9,
    gst: null
  }, {
    time: '09/12/2014 15:00',
    location: 'Location 1',
    wd: 129,
    wsp: 10.4,
    gst: null
  }, {
    time: '09/12/2014 16:00',
    location: 'Location 1',
    wd: 125,
    wsp: 11.0,
    gst: 19.3
  }, {
    time: '09/12/2014 17:00',
    location: 'Location 1',
    wd: 122,
    wsp: 10.2,
    gst: null
  }, {
    time: '09/12/2014 18:00',
    location: 'Location 1',
    wd: 119,
    wsp: 9.5,
    gst: null
  }, {
    time: '09/12/2014 19:00',
    location: 'Location 1',
    wd: 116,
    wsp: 8.8,
    gst: null
  }, {
    time: '09/12/2014 20:00',
    location: 'Location 1',
    wd: 112,
    wsp: 7.8,
    gst: null
  }, {
    time: '09/12/2014 21:00',
    location: 'Location 1',
    wd: 109,
    wsp: 6.8,
    gst: null
  }, {
    time: '09/12/2014 22:00',
    location: 'Location 1',
    wd: 107,
    wsp: 5.7,
    gst: 18.7
  }, {
    time: '09/12/2014 23:00',
    location: 'Location 1',
    wd: 107,
    wsp: 5.3,
    gst: null
  }, {
    time: '10/12/2014 00:00',
    location: 'Location 1',
    wd: 107,
    wsp: 4.8,
    gst: null
  }, {
    time: '10/12/2014 01:00',
    location: 'Location 1',
    wd: 107,
    wsp: 4.3,
    gst: null
  }, {
    time: '10/12/2014 02:00',
    location: 'Location 1',
    wd: 107,
    wsp: 4.2,
    gst: null
  }, {
    time: '10/12/2014 03:00',
    location: 'Location 1',
    wd: 107,
    wsp: 4.2,
    gst: null
  }, {
    time: '10/12/2014 04:00',
    location: 'Location 1',
    wd: 107,
    wsp: 4.2,
    gst: 9.5
  }, {
    time: '10/12/2014 05:00',
    location: 'Location 1',
    wd: 101,
    wsp: 4.4,
    gst: null
  }, {
    time: '10/12/2014 06:00',
    location: 'Location 1',
    wd: 94,
    wsp: 4.7,
    gst: null
  }, {
    time: '10/12/2014 07:00',
    location: 'Location 1',
    wd: 87,
    wsp: 5.0,
    gst: null
  }, {
    time: '10/12/2014 08:00',
    location: 'Location 1',
    wd: 78,
    wsp: 5.6,
    gst: null
  }, {
    time: '10/12/2014 09:00',
    location: 'Location 1',
    wd: 68,
    wsp: 6.1,
    gst: null
  }, {
    time: '10/12/2014 10:00',
    location: 'Location 1',
    wd: 58,
    wsp: 6.6,
    gst: 12.5
  }, {
    time: '10/12/2014 11:00',
    location: 'Location 1',
    wd: 58,
    wsp: 7.3,
    gst: null
  }, {
    time: '10/12/2014 12:00',
    location: 'Location 1',
    wd: 59,
    wsp: 7.9,
    gst: null
  }, {
    time: '10/12/2014 13:00',
    location: 'Location 1',
    wd: 60,
    wsp: 8.5,
    gst: null
  }, {
    time: '10/12/2014 14:00',
    location: 'Location 1',
    wd: 61,
    wsp: 9.3,
    gst: null
  }, {
    time: '10/12/2014 15:00',
    location: 'Location 1',
    wd: 61,
    wsp: 10.1,
    gst: null
  }, {
    time: '10/12/2014 16:00',
    location: 'Location 1',
    wd: 62,
    wsp: 10.9,
    gst: 18.6
  }, {
    time: '10/12/2014 17:00',
    location: 'Location 1',
    wd: 60,
    wsp: 10.6,
    gst: null
  }, {
    time: '10/12/2014 18:00',
    location: 'Location 1',
    wd: 59,
    wsp: 10.3,
    gst: null
  }, {
    time: '10/12/2014 19:00',
    location: 'Location 1',
    wd: 57,
    wsp: 10.0,
    gst: null
  }, {
    time: '10/12/2014 20:00',
    location: 'Location 1',
    wd: 53,
    wsp: 9.3,
    gst: null
  }, {
    time: '10/12/2014 21:00',
    location: 'Location 1',
    wd: 49,
    wsp: 8.6,
    gst: null
  }, {
    time: '10/12/2014 22:00',
    location: 'Location 1',
    wd: 45,
    wsp: 8.0,
    gst: 19.2
  }, {
    time: '10/12/2014 23:00',
    location: 'Location 1',
    wd: 60,
    wsp: 7.6,
    gst: null
  }, {
    time: '11/12/2014 00:00',
    location: 'Location 1',
    wd: 42,
    wsp: 7.3,
    gst: null
  }, {
    time: '11/12/2014 01:00',
    location: 'Location 1',
    wd: 43,
    wsp: 7.0,
    gst: null
  }, {
    time: '11/12/2014 02:00',
    location: 'Location 1',
    wd: 60,
    wsp: 7.0,
    gst: null
  }, {
    time: '11/12/2014 03:00',
    location: 'Location 1',
    wd: 50,
    wsp: 6.9,
    gst: null
  }, {
    time: '11/12/2014 04:00',
    location: 'Location 1',
    wd: 31,
    wsp: 7.0,
    gst: 14.3
  }, {
    time: '11/12/2014 05:00',
    location: 'Location 1',
    wd: 57,
    wsp: 7.6,
    gst: null
  }, {
    time: '11/12/2014 06:00',
    location: 'Location 1',
    wd: 125,
    wsp: 8.2,
    gst: null
  }, {
    time: '11/12/2014 07:00',
    location: 'Location 1',
    wd: 67,
    wsp: 8.8,
    gst: null
  }, {
    time: '11/12/2014 08:00',
    location: 'Location 1',
    wd: 111,
    wsp: 9.2,
    gst: null
  }, {
    time: '11/12/2014 09:00',
    location: 'Location 1',
    wd: 141,
    wsp: 9.6,
    gst: null
  }, {
    time: '11/12/2014 10:00',
    location: 'Location 1',
    wd: 136,
    wsp: 10.0,
    gst: 19.5
  }, {
    time: '11/12/2014 11:00',
    location: 'Location 1',
    wd: 149,
    wsp: 10.9,
    gst: null
  }, {
    time: '11/12/2014 12:00',
    location: 'Location 1',
    wd: 149,
    wsp: 11.8,
    gst: null
  }, {
    time: '11/12/2014 13:00',
    location: 'Location 1',
    wd: 147,
    wsp: 12.8,
    gst: null
  }, {
    time: '11/12/2014 14:00',
    location: 'Location 1',
    wd: 146,
    wsp: 14.0,
    gst: null
  }, {
    time: '11/12/2014 15:00',
    location: 'Location 1',
    wd: 144,
    wsp: 15.3,
    gst: null
  }, {
    time: '11/12/2014 16:00',
    location: 'Location 1',
    wd: 143,
    wsp: 16.6,
    gst: 28.6
  }, {
    time: '11/12/2014 17:00',
    location: 'Location 1',
    wd: 142,
    wsp: 16.6,
    gst: null
  }, {
    time: '11/12/2014 18:00',
    location: 'Location 1',
    wd: 141,
    wsp: 16.6,
    gst: null
  }, {
    time: '11/12/2014 19:00',
    location: 'Location 1',
    wd: 140,
    wsp: 16.6,
    gst: null
  }, {
    time: '11/12/2014 20:00',
    location: 'Location 1',
    wd: 139,
    wsp: 16.7,
    gst: null
  }, {
    time: '11/12/2014 21:00',
    location: 'Location 1',
    wd: 138,
    wsp: 16.7,
    gst: null
  }, {
    time: '11/12/2014 22:00',
    location: 'Location 1',
    wd: 138,
    wsp: 16.8,
    gst: 30.6
  }, {
    time: '11/12/2014 23:00',
    location: 'Location 1',
    wd: 139,
    wsp: 17.0,
    gst: null
  }, {
    time: '12/12/2014 00:00',
    location: 'Location 1',
    wd: 139,
    wsp: 17.4,
    gst: null
  }, {
    time: '12/12/2014 01:00',
    location: 'Location 1',
    wd: 140,
    wsp: 17.6,
    gst: null
  }, {
    time: '12/12/2014 02:00',
    location: 'Location 1',
    wd: 140,
    wsp: 17.8,
    gst: null
  }, {
    time: '12/12/2014 03:00',
    location: 'Location 1',
    wd: 141,
    wsp: 18.0,
    gst: null
  }, {
    time: '12/12/2014 04:00',
    location: 'Location 1',
    wd: 141,
    wsp: 18.2,
    gst: 31.4
  }, {
    time: '12/12/2014 05:00',
    location: 'Location 1',
    wd: 140,
    wsp: 18.4,
    gst: null
  }, {
    time: '12/12/2014 06:00',
    location: 'Location 1',
    wd: 140,
    wsp: 18.7,
    gst: null
  }, {
    time: '12/12/2014 07:00',
    location: 'Location 1',
    wd: 139,
    wsp: 18.9,
    gst: null
  }, {
    time: '12/12/2014 08:00',
    location: 'Location 1',
    wd: 138,
    wsp: 19.1,
    gst: null
  }, {
    time: '12/12/2014 09:00',
    location: 'Location 1',
    wd: 136,
    wsp: 19.3,
    gst: null
  }, {
    time: '12/12/2014 10:00',
    location: 'Location 1',
    wd: 135,
    wsp: 19.5,
    gst: 33.9
  }, {
    time: '12/12/2014 11:00',
    location: 'Location 1',
    wd: 135,
    wsp: 19.5,
    gst: null
  }, {
    time: '12/12/2014 12:00',
    location: 'Location 1',
    wd: 134,
    wsp: 19.5,
    gst: null
  }, {
    time: '12/12/2014 13:00',
    location: 'Location 1',
    wd: 134,
    wsp: 19.5,
    gst: null
  }, {
    time: '12/12/2014 14:00',
    location: 'Location 1',
    wd: 134,
    wsp: 19.4,
    gst: null
  }, {
    time: '12/12/2014 15:00',
    location: 'Location 1',
    wd: 135,
    wsp: 19.4,
    gst: null
  }, {
    time: '12/12/2014 16:00',
    location: 'Location 1',
    wd: 135,
    wsp: 19.4,
    gst: 34.0
  }, {
    time: '12/12/2014 17:00',
    location: 'Location 1',
    wd: 137,
    wsp: 18.8,
    gst: null
  }, {
    time: '12/12/2014 18:00',
    location: 'Location 1',
    wd: 138,
    wsp: 18.2,
    gst: null
  }, {
    time: '12/12/2014 19:00',
    location: 'Location 1',
    wd: 137,
    wsp: 17.7,
    gst: null
  }, {
    time: '12/12/2014 20:00',
    location: 'Location 1',
    wd: 138,
    wsp: 17.6,
    gst: null
  }, {
    time: '12/12/2014 21:00',
    location: 'Location 1',
    wd: 138,
    wsp: 17.5,
    gst: null
  }, {
    time: '12/12/2014 22:00',
    location: 'Location 1',
    wd: 136,
    wsp: 17.4,
    gst: 32.7
  }, {
    time: '12/12/2014 23:00',
    location: 'Location 1',
    wd: 137,
    wsp: 17.0,
    gst: null
  }, {
    time: '13/12/2014 00:00',
    location: 'Location 1',
    wd: 137,
    wsp: 16.6,
    gst: null
  }, {
    time: '13/12/2014 01:00',
    location: 'Location 1',
    wd: 137,
    wsp: 16.2,
    gst: null
  }, {
    time: '13/12/2014 02:00',
    location: 'Location 1',
    wd: 137,
    wsp: 15.9,
    gst: null
  }, {
    time: '13/12/2014 03:00',
    location: 'Location 1',
    wd: 137,
    wsp: 15.6,
    gst: null
  }, {
    time: '13/12/2014 04:00',
    location: 'Location 1',
    wd: 138,
    wsp: 15.3,
    gst: 28.4
  }, {
    time: '13/12/2014 05:00',
    location: 'Location 1',
    wd: 138,
    wsp: 15.4,
    gst: null
  }, {
    time: '13/12/2014 06:00',
    location: 'Location 1',
    wd: 140,
    wsp: 15.4,
    gst: null
  }, {
    time: '13/12/2014 07:00',
    location: 'Location 1',
    wd: 136,
    wsp: 15.5,
    gst: null
  }, {
    time: '13/12/2014 08:00',
    location: 'Location 1',
    wd: 139,
    wsp: 15.6,
    gst: null
  }, {
    time: '13/12/2014 09:00',
    location: 'Location 1',
    wd: 137,
    wsp: 15.7,
    gst: null
  }, {
    time: '13/12/2014 10:00',
    location: 'Location 1',
    wd: 136,
    wsp: 15.8,
    gst: 28.1
  }, {
    time: '13/12/2014 11:00',
    location: 'Location 1',
    wd: 137,
    wsp: 15.6,
    gst: null
  }, {
    time: '13/12/2014 12:00',
    location: 'Location 1',
    wd: 139,
    wsp: 15.4,
    gst: null
  }, {
    time: '13/12/2014 13:00',
    location: 'Location 1',
    wd: 142,
    wsp: 15.2,
    gst: null
  }, {
    time: '13/12/2014 14:00',
    location: 'Location 1',
    wd: 145,
    wsp: 15.0,
    gst: null
  }, {
    time: '13/12/2014 15:00',
    location: 'Location 1',
    wd: 147,
    wsp: 14.8,
    gst: null
  }, {
    time: '13/12/2014 16:00',
    location: 'Location 1',
    wd: 146,
    wsp: 14.5,
    gst: 27.5
  }, {
    time: '13/12/2014 17:00',
    location: 'Location 1',
    wd: 149,
    wsp: 13.9,
    gst: null
  }, {
    time: '13/12/2014 18:00',
    location: 'Location 1',
    wd: 150,
    wsp: 13.3,
    gst: null
  }, {
    time: '13/12/2014 19:00',
    location: 'Location 1',
    wd: 152,
    wsp: 12.7,
    gst: null
  }, {
    time: '13/12/2014 20:00',
    location: 'Location 1',
    wd: 152,
    wsp: 12.0,
    gst: null
  }, {
    time: '13/12/2014 21:00',
    location: 'Location 1',
    wd: 153,
    wsp: 11.4,
    gst: null
  }, {
    time: '13/12/2014 22:00',
    location: 'Location 1',
    wd: 153,
    wsp: 10.8,
    gst: 24.5
  }, {
    time: '13/12/2014 23:00',
    location: 'Location 1',
    wd: 166,
    wsp: 10.4,
    gst: null
  }, {
    time: '14/12/2014 00:00',
    location: 'Location 1',
    wd: 180,
    wsp: 10.0,
    gst: null
  }, {
    time: '14/12/2014 01:00',
    location: 'Location 1',
    wd: 197,
    wsp: 9.6,
    gst: null
  }, {
    time: '14/12/2014 02:00',
    location: 'Location 1',
    wd: 215,
    wsp: 9.2,
    gst: null
  }, {
    time: '14/12/2014 03:00',
    location: 'Location 1',
    wd: 231,
    wsp: 8.9,
    gst: null
  }, {
    time: '14/12/2014 04:00',
    location: 'Location 1',
    wd: 247,
    wsp: 8.5,
    gst: 17.2
  }, {
    time: '14/12/2014 05:00',
    location: 'Location 1',
    wd: 234,
    wsp: 8.4,
    gst: null
  }, {
    time: '14/12/2014 06:00',
    location: 'Location 1',
    wd: 218,
    wsp: 8.2,
    gst: null
  }, {
    time: '14/12/2014 07:00',
    location: 'Location 1',
    wd: 203,
    wsp: 8.1,
    gst: null
  }, {
    time: '14/12/2014 08:00',
    location: 'Location 1',
    wd: 190,
    wsp: 8.0,
    gst: null
  }, {
    time: '14/12/2014 09:00',
    location: 'Location 1',
    wd: 189,
    wsp: 7.8,
    gst: null
  }, {
    time: '14/12/2014 10:00',
    location: 'Location 1',
    wd: 233,
    wsp: 7.8,
    gst: 17.4
  }, {
    time: '14/12/2014 11:00',
    location: 'Location 1',
    wd: 182,
    wsp: 8.0,
    gst: null
  }, {
    time: '14/12/2014 12:00',
    location: 'Location 1',
    wd: 163,
    wsp: 8.4,
    gst: null
  }, {
    time: '14/12/2014 13:00',
    location: 'Location 1',
    wd: 146,
    wsp: 8.7,
    gst: null
  }, {
    time: '14/12/2014 14:00',
    location: 'Location 1',
    wd: 131,
    wsp: 9.1,
    gst: null
  }, {
    time: '14/12/2014 15:00',
    location: 'Location 1',
    wd: 117,
    wsp: 9.4,
    gst: null
  }, {
    time: '14/12/2014 16:00',
    location: 'Location 1',
    wd: 105,
    wsp: 9.8,
    gst: 20.1
  }, {
    time: '14/12/2014 17:00',
    location: 'Location 1',
    wd: 112,
    wsp: 9.4,
    gst: null
  }, {
    time: '14/12/2014 18:00',
    location: 'Location 1',
    wd: 117,
    wsp: 8.9,
    gst: null
  }, {
    time: '14/12/2014 19:00',
    location: 'Location 1',
    wd: 120,
    wsp: 8.5,
    gst: null
  }, {
    time: '14/12/2014 20:00',
    location: 'Location 1',
    wd: 120,
    wsp: 8.1,
    gst: null
  }, {
    time: '14/12/2014 21:00',
    location: 'Location 1',
    wd: 120,
    wsp: 7.7,
    gst: null
  }, {
    time: '14/12/2014 22:00',
    location: 'Location 1',
    wd: 114,
    wsp: 7.3,
    gst: 19.0
  }, {
    time: '14/12/2014 23:00',
    location: 'Location 1',
    wd: 128,
    wsp: 7.0,
    gst: null
  }
];
