// Generated by CoffeeScript 1.9.2

/*

Using DVE with browserify is recommended but not required.
 */
var components, curve, d3, fixdata, jsyaml, moment;

curve = function(x) {
  if (x < 0.25) {
    return 8 * x * x;
  }
  if (x < 0.75) {
    return -8 * (x - 0.5) * (x - 0.5) + 1;
  }
  return 8 * (x - 1) * (x - 1);
};

d3 = require('d3');

jsyaml = require('js-yaml');

components = require('dve');

moment = require('timespanner');

fixdata = function(data) {
  var d, i, len, results;
  results = [];
  for (i = 0, len = data.length; i < len; i++) {
    d = data[i];
    d.time = moment(d.time, 'DD-MM-YYYY HH:mm');
    d.wsp = parseFloat(d.wsp);
    d.wsp2 = parseFloat(d.wsp);
    d.wd = parseFloat(d.wd);
    results.push(d.gust = parseFloat(d.gust));
  }
  return results;
};

d3.csv('/example3.csv', function(err, example3) {
  fixdata(example3);
  return d3.text('/test.yml', function(error, spec) {
    var adjustedrange, dom, scene;
    dom = document.querySelector('#root');
    spec = jsyaml.load(spec);
    scene = components[spec.type](spec, components);
    scene.render(dom, {
      data: example3
    }, {});
    adjustedrange = null;
    scene.hub.on('range', function(range) {
      if (range == null) {
        return adjustedrange = null;
      }
      return adjustedrange = range.p1 <= range.p2 ? {
        p1: range.p1,
        p2: range.p2
      } : {
        p1: range.p2,
        p2: range.p1
      };
    });
    document.querySelector('button.up').onclick = function(e) {
      var d, diff, i, len, p1, p2, x;
      if (adjustedrange == null) {
        return;
      }
      p1 = adjustedrange.p1.format('x');
      p2 = adjustedrange.p2.format('x');
      diff = p2 - p1;
      for (i = 0, len = example3.length; i < len; i++) {
        d = example3[i];
        x = d.time.format('x') - p1;
        if (diff === 0) {
          if (x === 0) {
            d.wsp2 += 1;
          } else {
            continue;
          }
        }
        x /= diff;
        if (x >= 0 && x <= 1) {
          d.wsp2 += curve(x);
        }
      }
      return scene.hub.emit('state updated', {
        data: example3
      });
    };
    document.querySelector('button.down').onclick = function(e) {
      var d, diff, i, len, p1, p2, x;
      if (adjustedrange == null) {
        return;
      }
      p1 = adjustedrange.p1.format('x');
      p2 = adjustedrange.p2.format('x');
      diff = p2 - p1;
      for (i = 0, len = example3.length; i < len; i++) {
        d = example3[i];
        x = d.time.format('x') - p1;
        if (diff === 0) {
          if (x === 0) {
            d.wsp2 -= 1;
          } else {
            continue;
          }
        }
        x /= diff;
        if (x >= 0 && x <= 1) {
          d.wsp2 -= curve(x);
        }
      }
      return scene.hub.emit('state updated', {
        data: example3
      });
    };
    document.querySelector('button.back').onclick = function(e) {
      return scene.hub.emit('range nudge back');
    };
    return document.querySelector('button.forward').onclick = function(e) {
      return scene.hub.emit('range nudge forward');
    };
  });
});
