// Generated by CoffeeScript 1.9.2
var listcomponent;

listcomponent = require('./list');

module.exports = function(spec, components) {
  var list, odoql;
  list = listcomponent(spec.spec, components);
  return odoql = {
    init: function(state, params) {
      return list.init(state, params);
    },
    render: function(dom, state, params) {
      return list.render(dom, state, params);
    },
    resize: function(dimensions) {
      return list.resize(dimensions);
    },
    query: function(params) {
      return spec.queries;
    },
    remove: function(dom, state, params) {
      return list.remove(dom, state, params);
    }
  };
};
