// Generated by CoffeeScript 1.9.2
var createhub, extend, listcomponent;

createhub = require('../util/hub');

listcomponent = require('./list');

extend = require('extend');

module.exports = function(spec, components) {
  var hub, list;
  list = listcomponent(spec.spec, components);
  hub = createhub();
  return {
    render: function(dom, state, params) {
      var newparams;
      newparams = extend({}, params, {
        hub: hub
      });
      return list.render(dom, state, newparams);
    },
    resize: function(dimensions) {
      return list.resize(dimensions);
    },
    query: function(params) {
      return spec.queries;
    },
    hub: hub
  };
};
