// Generated by CoffeeScript 1.9.2

/*

List components.
 */
module.exports = function(spec, components) {
  var items, list;
  if (!(spec instanceof Array)) {
    spec = [spec];
  }
  items = [];
  return list = {
    render: function(dom, state, params) {
      var item, j, len, s;
      for (j = 0, len = spec.length; j < len; j++) {
        s = spec[j];
        if (components[s.type] == null) {
          return console.error(s.type + " component not found");
        }
        item = components[s.type](s, components);
        item.render(dom, state, params);
        items.push(item);
      }
    },
    resize: function(dimensions) {
      var i, j, len, results;
      results = [];
      for (j = 0, len = items.length; j < len; j++) {
        i = items[j];
        if (i.resize == null) {
          continue;
        }
        results.push(i.resize(dimensions));
      }
      return results;
    },
    query: function(params) {
      var item, j, key, len, query, ref, result;
      result = {};
      for (j = 0, len = items.length; j < len; j++) {
        item = items[j];
        if (item.query != null) {
          ref = item.query(params);
          for (key in ref) {
            query = ref[key];
            result[key] = query;
          }
        }
      }
      return result;
    }
  };
};
