// Generated by CoffeeScript 1.9.2
var createhub, extend, listcomponent, moment;

moment = require('timespanner');

createhub = require('../util/hub');

listcomponent = require('./list');

extend = require('extend');

module.exports = function(spec, components) {
  var list;
  list = listcomponent(spec.spec, components);
  return {
    init: function(state, params) {
      return list.init(state, params);
    },
    render: function(dom, state, params) {
      var poi, tz;
      poi = null;
      if (moment.utc().isBetween(params.domain[0], params.domain[1])) {
        tz = params.domain[0].tz();
        poi = moment.utc().tz(tz);
      }
      list.render(dom, state, params);
      if (params.hub != null) {
        return params.hub.emit('poi', poi);
      }
    },
    resize: function(dimensions) {
      return list.resize(dimensions);
    },
    query: function(params) {
      return spec.queries;
    },
    remove: function(dom, state, params) {
      return list.remove(dom, state, params);
    }
  };
};
