// Generated by CoffeeScript 1.9.1

/*

Represents an entire report.
Includes title, author and other metadata.
 */
var mount;

mount = require('./mount');

module.exports = function(dom, options) {
  var components, spec;
  components = options.components, spec = options.spec;
  return mount(dom, {
    components: components,
    spec: spec.spec
  });
};
