// Generated by CoffeeScript 1.9.1

/*

Create some breathing room in your visualisations.
Has a default height, or height can be specified.

- type: space
  height: 50
 */
var d3;

d3 = require('d3');

module.exports = function(dom, options) {
  var dimensions, resize, spec;
  dimensions = options.dimensions, spec = options.spec;
  dom = d3.select(dom).append('div').attr('class', 'item space');
  resize = function(dimensions) {
    return dom.style('width', dimensions[0] + "px").style('height', (spec.height || 15) + "px");
  };
  resize(dimensions);
  return {
    resize: resize
  };
};
