// Generated by CoffeeScript 1.9.2
var createhub, d3, extend, listcomponent, moment;

d3 = require('d3');

moment = require('timespanner');

createhub = require('../util/hub');

listcomponent = require('./list');

extend = require('extend');

module.exports = function(spec, components) {
  var list, timedomain;
  list = listcomponent(spec.spec, components);
  return timedomain = {
    render: function(dom, state, params) {
      var d, data, domain, i, len, newparams;
      data = state.data;
      for (i = 0, len = data.length; i < len; i++) {
        d = data[i];
        d.time = moment.utc(d.time, moment.ISO_8601);
      }
      domain = d3.extent(data, function(d) {
        return d.time;
      });
      if (spec.start != null) {
        domain[0] = spec.start;
        if (typeof domain[0] === 'string') {
          domain[0] = moment.spanner(domain[0]);
        }
      }
      if (spec.end != null) {
        domain[1] = spec.end;
        if (typeof domain[1] === 'string') {
          domain[1] = moment.spanner(domain[1]);
        }
      }
      newparams = extend({}, params, {
        domain: domain
      });
      return list.render(dom, state, newparams);
    },
    resize: function(dimensions) {
      return list.resize(dimensions);
    },
    query: function(params) {
      return spec.queries;
    }
  };
};
