// Generated by CoffeeScript 1.9.3
var components, d3, jsyaml, moment;

d3 = require('d3');

jsyaml = require('js-yaml');

components = require('dve');

moment = require('timespanner');

d3.json('/wsp-mean.json', function(errData, data) {
  return d3.text('/spec.yml', function(errSpec, spec) {
    var el, scene;
    el = document.getElementById('histogram');
    spec = jsyaml.load(spec);
    scene = components[spec.type](spec, components);
    scene.init({
      data: data
    }, {});
    return scene.render(el, {
      data: data
    }, {});
  });
});
